### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by backcountrymountains** [endrl/jellyfin-plugin-edl#1]
I'm running jellyfin using docker compose:
Server: jellyfin
Version: 10.8.11
Operating System: Linux
Architecture: X64

Okay, it seems that this is for jellyfin 10.9.0.0 but I'm using the latest jellyfin build for docker, 10.8.11.

Is it possible to make this work with 10.8.11?

**Comment by endrl** [comment]
Thank you for reaching out. Currently, this is not compatible with official Jellyfin. I provide a custom build for testing purposes. See https://github.com/endrl/segment-editor#installation

**Comment by endrl** [comment]
The latest version of the plugin is for Jellyfin 10.10 unstable. I can't create a version for jellyfin 10.9/10.8
